import './mutations/clipboard.mutation';
import './mutations/data.mutation';
import './mutations/markdown.mutation';
import './mutations/extension.mutation';
import './mutations/sol.mutation';
import './mutations/workspace.mutation';
import './mutations/text.mutation';
import './mutations/url.mutation';
import './mutations/storage-item.mutation';
