import './mutations/clipboard.mutation';
import './mutations/data.mutation';
import './mutations/extension.mutation';
import './mutations/sol.mutation';
import './mutations/sol-extension.mutation';
import './mutations/sol-workspace.mutation';
import './mutations/text.mutation';
import './mutations/url.mutation';
import './mutations/storage-item.mutation';
