import './modules/data/setup';
import './modules/globals/setup';
import './modules/integrations/setup';
import './modules/os/setup';
import './modules/play/setup';
import './modules/sol/setup';
import './modules/storage/setup';
import './modules/utils/setup';
import './modules/web/setup';
